// Picks the trick shots for the game from what tools/gen-tricks.mjs found, checks each once more through the real
// physics (with the hint as it will be stored), names them, and writes src/tricks-data.js.
//
//   node tools/build-tricks.mjs <dir with the .jsonl files> [per-size limits, e.g. 8,8,4]
import fs from 'node:fs'
import path from 'node:path'
import {attempt} from '../src/drills.js'
import {setTableSize} from '../src/table.js'
setTableSize(7)

const dir=process.argv[2]
const LIMIT=(process.argv[3]||'8,8,4').split(',').map(Number)   // for 2, 3 and 4 balls
const NAMES={
 2:['Two for one','Kiss and drop','Double trouble','Tandem','Tag team','Follow me','Buddy system','Pair of aces','Side by side','Twin peaks'],
 3:['Hat trick','Triple play','Trifecta','Domino','Chain reaction','Three of a kind','Trio','Cascade','Three-ring circus','Threesome'],
 4:['Clean sweep','Grand slam','Four on the floor','Full house','Quadruple','Everything must go']
}

const found=[]
for(const f of fs.readdirSync(dir).filter(f=>f.endsWith('.jsonl')))
 for(const line of fs.readFileSync(path.join(dir,f),'utf8').split('\n').filter(Boolean))found.push(JSON.parse(line))

const proven=found.filter(t=>{
 const drill={layout:{cue:t.cue,balls:t.ballsAt},win:{clear:true}}
 return attempt(drill,t.hint).ok
})
const seen=new Set()
const out=[]
for(const k of [2,3,4]){
 const pool=proven.filter(t=>t.balls===k).sort((a,b)=>b.window-a.window)
 let n=0
 for(const t of pool){
  const key=JSON.stringify(t.ballsAt)
  if(seen.has(key))continue
  seen.add(key)
  if(n>=(LIMIT[k-2]||0))break
  out.push({id:`trick-${String(out.length+1).padStart(2,'0')}`,name:NAMES[k][n]||`${k} balls ${n+1}`,cue:t.cue,balls:t.ballsAt,hint:t.hint,window:t.window})
  n++
 }
 console.error(`${k} balls: ${found.filter(t=>t.balls===k).length} found, ${pool.length} proven, using ${n}`)
}
const body=out.map(t=>' '+JSON.stringify(t)).join(',\n')
fs.writeFileSync(new URL('../src/tricks-data.js',import.meta.url),`// Generated by tools/build-tricks.mjs -- do not edit by hand.\n// Each entry: a table (the cue ball and the balls to clear), one shot proven to clear it, and how many degrees of aim still do.\nexport const TRICKS=[\n${body}\n]\n`)
console.error(`wrote ${out.length} trick shots`)
