// Generates the daily shots: fixed, solver-proven layouts, so that everyone who opens
// "Daily shot" on a given day gets the same table, and every one of them can be solved.
//
//   node tools/gen-daily.mjs [count]     writes src/daily-data.js
//
// Layouts are drawn from a seeded generator, then kept only if a real search of the
// physics finds a shot with a comfortable margin for error. The result is written out as
// data, so nothing about the day's table depends on the player's browser.
import fs from 'node:fs'
import {attempt} from '../src/drills.js'
import {POCKETS,W,H,R,setTableSize} from '../src/table.js'
setTableSize(7)   // the table the game really plays: its pockets are a hair smaller than the module default

const COUNT=Number(process.argv[2])||180
const MARGIN=48          // keep everything well off the cushions
const MIN_WINDOW=1.0     // degrees of aim that still work; below this it is a lottery

function rng(seed){let a=seed>>>0;return()=>{a=(a+0x6D2B79F5)>>>0;let t=a;t=Math.imul(t^(t>>>15),t|1);t^=t+Math.imul(t^(t>>>7),t|61);return((t^(t>>>14))>>>0)/4294967296}}

function layout(r){
 const pos=[]
 const place=()=>{for(let i=0;i<200;i++){
  const p=[Math.round(MARGIN+r()*(W-2*MARGIN)),Math.round(MARGIN+r()*(H-2*MARGIN))]
  if(pos.every(q=>Math.hypot(q[0]-p[0],q[1]-p[1])>R*3.2)&&POCKETS.every(k=>Math.hypot(k[0]-p[0],k[1]-p[1])>R*4))return p}
  return null}
 const cue=place();if(!cue)return null;pos.push(cue)
 const others=1+Math.floor(r()*3)                       // the target plus up to two more in the way
 const nums=[1,2,3,4,5,6,7].sort(()=>r()-.5).slice(0,others)
 const balls=[]
 for(const n of nums){const p=place();if(!p)return null;pos.push(p);balls.push([n,p[0],p[1]])}
 return {cue,balls,target:balls[0][0]}
}

const POWERS=[30,50,70,90]
const angleTo=(a,b)=>Math.atan2(b[1]-a[1],b[0]-a[0])
function candidates(l){
 const t=l.balls[0],out=[]
 for(const k of POCKETS){
  const u=[k[0]-t[1],k[1]-t[2]],m=Math.hypot(...u),g=[t[1]-u[0]/m*2*R,t[2]-u[1]/m*2*R]
  const base=angleTo(l.cue,g)
  for(let d=-3;d<=3;d+=.25)out.push(base+d*Math.PI/180)
 }
 return out
}
const windowDegrees=(drill,shot)=>{
 const ok=d=>attempt(drill,{...shot,angle:shot.angle+d*Math.PI/180}).ok
 let lo=0,hi=0
 while(lo>-5&&ok(lo-.05))lo-=.05
 while(hi<5&&ok(hi+.05))hi+=.05
 return Math.round((hi-lo+.05)*100)/100
}

const out=[]
let seed=1
while(out.length<COUNT&&seed<200000){
 const l=layout(rng(seed++));if(!l)continue
 const drill={layout:{cue:l.cue,balls:l.balls},win:{pot:l.target}}
 let best=null
 for(const angle of candidates(l))for(const power of POWERS){
  const shot={angle,power,spin:[0,0]}
  if(!attempt(drill,shot).ok)continue
  const w=windowDegrees(drill,shot)
  if(!best||w>best.window)best={shot,window:w}
 }
 if(!best||best.window<MIN_WINDOW)continue
 out.push({seed:seed-1,cue:l.cue,balls:l.balls,target:l.target,hint:{angle:Math.round(best.shot.angle*10000)/10000,power:best.shot.power,spin:[0,0]},window:best.window})
 if(out.length%10===0)console.error(`${out.length}/${COUNT} (tried ${seed-1} layouts)`)
}
const body=out.map(d=>` ${JSON.stringify(d)}`).join(',\n')
fs.writeFileSync(new URL('../src/daily-data.js',import.meta.url),`// Generated by tools/gen-daily.mjs -- do not edit by hand.\n// Each entry: a table, the ball to pot, a shot proven to pot it, and how many degrees of aim still work.\nexport const DAILY=[\n${body}\n]\n`)
console.error(`wrote ${out.length} daily shots`)
