// Keeps only the daily shots whose hint still solves them on the table the game really plays
// (setTableSize(7)), with at least MIN_WINDOW degrees to spare there.
import fs from 'node:fs'
import {DAILY} from '../src/daily-data.js'
import {attempt} from '../src/drills.js'
import {setTableSize} from '../src/table.js'
setTableSize(7)
const MIN_WINDOW=1.0
const windowDegrees=(drill,shot)=>{
 const ok=d=>attempt(drill,{...shot,angle:shot.angle+d*Math.PI/180}).ok
 let lo=0,hi=0
 while(lo>-5&&ok(lo-.05))lo-=.05
 while(hi<5&&ok(hi+.05))hi+=.05
 return Math.round((hi-lo+.05)*100)/100
}
const keep=[]
for(const e of DAILY){
 const drill={layout:{cue:e.cue,balls:e.balls},win:{pot:e.target}}
 if(!attempt(drill,e.hint).ok){console.error('drop (hint fails)',e.seed);continue}
 const w=windowDegrees(drill,e.hint)
 if(w<MIN_WINDOW){console.error('drop (window',w,')',e.seed);continue}
 keep.push({...e,window:w})
}
const body=keep.map(d=>` ${JSON.stringify(d)}`).join(',\n')
fs.writeFileSync(new URL('../src/daily-data.js',import.meta.url),`// Generated by tools/gen-daily.mjs (and filtered by tools/refilter-daily.mjs on the real 7 ft table) -- do not edit by hand.\n// Each entry: a table, the ball to pot, a shot proven to pot it, and how many degrees of aim still work.\nexport const DAILY=[\n${body}\n]\n`)
console.error(`kept ${keep.length} of ${DAILY.length}`)
