// Generated by tools/build-tricks.mjs -- do not edit by hand.
// Each entry: a table (the cue ball and the balls to clear), one shot proven to clear it, and how many degrees of aim still do.
export const TRICKS=[
 {"id":"trick-01","name":"Two for one","cue":[247,167],"balls":[[1,568,200],[2,568,250]],"hint":{"angle":0.733,"power":80,"spin":[0,0]},"window":0.25},
 {"id":"trick-02","name":"Kiss and drop","cue":[264,248],"balls":[[1,552,193],[2,300,244]],"hint":{"angle":6.2657,"power":60,"spin":[0,-0.45]},"window":0.25},
 {"id":"trick-03","name":"Double trouble","cue":[435,203],"balls":[[1,356,199],[2,186,244]],"hint":{"angle":3.2812,"power":80,"spin":[0,0.45]},"window":0.25},
 {"id":"trick-04","name":"Tandem","cue":[587,123],"balls":[[1,194,159],[2,185,289]],"hint":{"angle":2.5133,"power":100,"spin":[0,0]},"window":0.25},
 {"id":"trick-05","name":"Tag team","cue":[246,148],"balls":[[1,344,215],[2,500,246]],"hint":{"angle":5.3582,"power":80,"spin":[0,0.45]},"window":0.2},
 {"id":"trick-06","name":"Follow me","cue":[562,176],"balls":[[1,439,300],[2,481,170]],"hint":{"angle":3.1765,"power":100,"spin":[0,0.45]},"window":0.15},
 {"id":"trick-07","name":"Buddy system","cue":[119,117],"balls":[[1,429,138],[2,75,209]],"hint":{"angle":4.2062,"power":80,"spin":[0,-0.45]},"window":0.15},
 {"id":"trick-08","name":"Pair of aces","cue":[326,266],"balls":[[1,596,151],[2,357,242]],"hint":{"angle":5.6025,"power":100,"spin":[0,-0.45]},"window":0.15},
 {"id":"trick-09","name":"Hat trick","cue":[488,206],"balls":[[1,189,206],[2,469,150],[3,77,119]],"hint":{"angle":4.3459,"power":100,"spin":[0.45,0]},"window":0.25},
 {"id":"trick-10","name":"Triple play","cue":[148,260],"balls":[[1,136,196],[2,311,186],[3,276,206]],"hint":{"angle":4.66,"power":80,"spin":[-0.45,0]},"window":0.25},
 {"id":"trick-11","name":"Trifecta","cue":[357,167],"balls":[[1,315,216],[2,247,189],[3,99,155]],"hint":{"angle":3.6652,"power":100,"spin":[0,0]},"window":0.15},
 {"id":"trick-12","name":"Domino","cue":[450,80],"balls":[[1,346,99],[2,313,227],[3,279,231]],"hint":{"angle":3.4208,"power":100,"spin":[0.45,0]},"window":0.15},
 {"id":"trick-13","name":"Chain reaction","cue":[351,207],"balls":[[1,392,177],[2,93,313],[3,396,239]],"hint":{"angle":5.5676,"power":100,"spin":[0,0]},"window":0.1},
 {"id":"trick-14","name":"Three of a kind","cue":[501,264],"balls":[[1,598,201],[2,418,161],[3,473,195]],"hint":{"angle":4.5379,"power":80,"spin":[0,-0.45]},"window":0.1},
 {"id":"trick-15","name":"Trio","cue":[389,232],"balls":[[1,441,249],[2,353,250],[3,320,143]],"hint":{"angle":1.7279,"power":100,"spin":[0,-0.45]},"window":0.1},
 {"id":"trick-16","name":"Cascade","cue":[379,83],"balls":[[1,603,217],[2,434,147],[3,410,219]],"hint":{"angle":0.6632,"power":60,"spin":[0,0.45]},"window":0.1},
 {"id":"trick-17","name":"Clean sweep","cue":[332,150],"balls":[[1,464,107],[2,384,216],[3,351,130],[4,356,175]],"hint":{"angle":6.1541,"power":94,"spin":[0.45,0]},"window":0.15},
 {"id":"trick-18","name":"Grand slam","cue":[357,167],"balls":[[1,315,216],[2,247,189],[3,99,155],[4,242,218]],"hint":{"angle":3.6652,"power":100,"spin":[0,0]},"window":0.15},
 {"id":"trick-19","name":"Four on the floor","cue":[488,206],"balls":[[1,189,206],[2,469,150],[3,77,119],[4,407,302]],"hint":{"angle":4.3459,"power":100,"spin":[0.45,0]},"window":0.1},
 {"id":"trick-20","name":"Full house","cue":[389,232],"balls":[[1,441,249],[2,353,250],[3,320,143],[4,406,83]],"hint":{"angle":1.7279,"power":100,"spin":[0,-0.45]},"window":0.1}
]
